### ISSUE TITLE
Make github account

### ISSUE THREAD

**Issue by rydcohen** [jvivian/rnaseq-recompute-analysis#22]

**Comment by jvivian** [comment]
Thanks @rydcohen !  I'll be making some issues for you soon, just have to deal with some car stuff.

**Comment by rydcohen** [comment]
Sounds great!  I couldn't figure out how to assign the issue to you, I'm
not sure if it'll be relevant in the future.  Hope all goes well with your
car stuff.

**Comment by jvivian** [comment]
There's an _assignees_ tab to the right with a little cog that you can click on to select someone.
