### ISSUE TITLE
Signup for Gene Analytics

### ISSUE THREAD

**Issue by jvivian** [jvivian/rnaseq-recompute-analysis#32]
Benedict gave the go-ahead. Will save tons of time when it comes to analyzing our gene sets.

**Comment by rydcohen** [comment]
Great, just signed up for it.  Should I let it run the free trial unit Benedict gives us an access code to upgrade?

**Comment by jvivian** [comment]
Waiting on Gina to send them a purchase order

**Comment by jvivian** [comment]
Still waiting on the purchase order...
